nome = input("Digite seu nome completo: ").strip()
maius = nome.upper()
minu = nome.lower()
tamanho = len(nome)-nome.count(' ')
prnome = nome.split()
print(f"{maius}")
print(f'{minu}')
print(f"{tamanho}")
print(f'{len(prnome[0])}')